# Generated by Django 5.1.2 on 2024-10-08 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_quizsession_player_quizsession_players"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizsession",
            name="score",
        ),
        migrations.AddField(
            model_name="quizsession",
            name="current_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.question",
            ),
        ),
    ]
