# Generated by Django 5.1.2 on 2024-10-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_quizsession_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(max_length=400),
        ),
    ]
