# Generated by Django 5.1.2 on 2024-10-08 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_question_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="number_of_answers",
        ),
        migrations.RemoveField(
            model_name="question",
            name="type",
        ),
    ]
