# Generated by Django 5.1.2 on 2024-10-08 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.quizsession",
            ),
        ),
    ]
